In [1]:
import numpy as np


# Matrix addition using NumPy
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

addition_result = matrix1 + matrix2
print("NumPy Matrix Addition Result:")
print(addition_result)

# Matrix multiplication using NumPy
matrix3 = np.array([[1, 2], [3, 4]])
matrix4 = np.array([[5, 6], [7, 8]])

multiplication_result = np.dot(matrix3, matrix4)
print("\nNumPy Matrix Multiplication Result:")
print(multiplication_result)

NumPy Matrix Addition Result:
[[ 8 10 12]
 [14 16 18]]

NumPy Matrix Multiplication Result:
[[19 22]
 [43 50]]
