In [1]:
import numpy as np


# Creating matrices of different dimensions
matrix_2x3 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix_3x2 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

matrix_3x3 = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

# Performing matrix operations with matrices of different dimensions
print("Matrix 2x3:")
print(matrix_2x3)
print("Shape:", matrix_2x3.shape)

print("\nMatrix 3x2:")
print(matrix_3x2)
print("Shape:", matrix_3x2.shape)

print("\nMatrix 3x3:")
print(matrix_3x3)
print("Shape:", matrix_3x3.shape)

# Multiplication example with matrices of different dimensions
result_2x2 = np.dot(matrix_2x3, matrix_3x2)
print("\nResult of multiplying 2x3 and 3x2 matrices (2x2):")
print(result_2x2)
print("Shape:", result_2x2.shape)

Matrix 2x3:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Matrix 3x2:
[[ 7  8]
 [ 9 10]
 [11 12]]
Shape: (3, 2)

Matrix 3x3:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Shape: (3, 3)

Result of multiplying 2x3 and 3x2 matrices (2x2):
[[ 58  64]
 [139 154]]
Shape: (2, 2)
