In [1]:
import numpy as np


# Create a sample matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Perform Singular Value Decomposition
U, S, V = np.linalg.svd(matrix)

# Reconstruct the original matrix from U, S, and V
reconstructed_matrix = U @ np.diag(S) @ V

print("Original Matrix:")
print(matrix)
print("\nSingular Value Decomposition (SVD) components:")
print("U:")
print(U)
print("\nS:")
# S is a 1D array containing singular values; converting to a diagonal matrix
print(np.diag(S))
print("\nV:")
print(V)
print("\nReconstructed Matrix:")
print(reconstructed_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Singular Value Decomposition (SVD) components:
U:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

S:
[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]

V:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

Reconstructed Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
